# Generated by Django 2.2.3 on 2019-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='djflow', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
            },
        ),
    ]
