# Generated by Django 2.2.3 on 2019-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='django_intranet_base', max_length=255),
        ),
    ]
