# Generated by Django 2.2.1 on 2019-05-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
