# Generated by Django 2.2.1 on 2019-06-12 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartola',
            name='title',
        ),
        migrations.AddField(
            model_name='cartola',
            name='desde',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 12, 22, 12, 795195), verbose_name='Movimientos desde'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartola',
            name='hasta',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 12, 22, 19, 290209), verbose_name='Movimientos hasta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartola',
            name='rut',
            field=models.CharField(default=datetime.datetime(2019, 6, 12, 12, 22, 22, 187031), max_length=50, verbose_name='Rut de gremio'),
            preserve_default=False,
        ),
    ]
