# Generated by Django 2.2.1 on 2019-06-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0002_auto_20190612_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='path',
            field=models.CharField(max_length=200, null=True, verbose_name='Directorio de archivo de cartolas'),
        ),
    ]
