# Generated by Django 2.2.1 on 2019-05-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0002_document_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('path', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
