# Generated by Django 2.2.1 on 2019-05-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0003_cartola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
