# Generated by Django 2.2.1 on 2019-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0004_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
