# Generated by Django 2.2.1 on 2019-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0004_cartola_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartola',
            name='path',
        ),
        migrations.AlterField(
            model_name='cartola',
            name='pdf_file',
            field=models.FileField(upload_to='C:\\Users\\francisco.bahamondes\\code\\django\\sistema_publicaciones_hipicas\\media/cartolas_gremios', verbose_name='Archivo PDF de cartola'),
        ),
    ]
