# Generated by Django 2.2.1 on 2019-06-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartolas_gremios', '0005_auto_20190615_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='pdf_file',
            field=models.FileField(max_length=300, upload_to='C:\\Users\\francisco.bahamondes\\code\\django\\sistema_publicaciones_hipicas\\media', verbose_name='Archivo PDF de cartola'),
        ),
    ]
