# Generated by Django 2.2.1 on 2019-06-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartolas_gremios', '0006_auto_20190615_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartola',
            name='rut',
        ),
        migrations.AddField(
            model_name='cartola',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartola',
            name='pdf_file',
            field=models.FileField(max_length=300, upload_to='C:\\Users\\francisco.bahamondes\\code\\django\\sistema_publicaciones_hipicas\\media/cartolas_gremios', verbose_name='Archivo PDF de cartola'),
        ),
    ]
