# Generated by Django 2.2.1 on 2019-07-07 01:24

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=common.models.img_url),
        ),
    ]
