# Generated by Django 2.2.3 on 2019-07-18 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutGremio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='Rut de gremio')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField(verbose_name='Movimientos desde')),
                ('hasta', models.DateTimeField(verbose_name='Movimientos hasta')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('pdf_file', models.FileField(max_length=300, upload_to='../media/cartolas_gremios', verbose_name='Archivo PDF de cartola')),
                ('is_active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rut_gremio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gremios.RutGremio')),
            ],
        ),
    ]
