# Generated by Django 2.2.1 on 2019-06-22 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField(verbose_name='Movimientos desde')),
                ('hasta', models.DateTimeField(verbose_name='Movimientos hasta')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('pdf_file', models.FileField(max_length=300, upload_to='C:\\Users\\francisco.bahamondes\\code\\django\\sistema_publicaciones_hipicas\\media/cartolas_gremios', verbose_name='Archivo PDF de cartola')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
