# Generated by Django 2.2.1 on 2019-06-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gremios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartola',
            name='user_id',
        ),
        migrations.CreateModel(
            name='RutGremio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='Rut de gremio')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
