# Generated by Django 2.2.1 on 2019-06-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gremios', '0002_auto_20190622_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartola',
            name='rut_gremio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gremios.RutGremio'),
            preserve_default=False,
        ),
    ]
