# Generated by Django 2.2.1 on 2019-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremios', '0003_cartola_rut_gremio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartola',
            name='rut_gremio_id',
        ),
        migrations.AddField(
            model_name='cartola',
            name='rut_gremio',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
