# Generated by Django 2.2.1 on 2019-06-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremios', '0006_rutgremio_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='pdf_file',
            field=models.FileField(max_length=300, upload_to='../media/cartolas_gremios', verbose_name='Archivo PDF de cartola'),
        ),
    ]
