# Generated by Django 2.2.3 on 2019-07-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gremios', '0007_auto_20190625_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutgremio',
            name='user_id',
        ),
    ]
