# Generated by Django 2.2.3 on 2019-07-13 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gremios', '0008_remove_rutgremio_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartola',
            name='rut_gremio',
        ),
        migrations.AddField(
            model_name='cartola',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartola',
            name='rut_gremio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gremios.RutGremio'),
        ),
        migrations.AddField(
            model_name='cartola',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rutgremio',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rutgremio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutgremio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rutgremio',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
