# Generated by Django 2.2.3 on 2019-07-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gremios', '0009_auto_20190713_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartola',
            name='rut_gremio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gremios.RutGremio'),
            preserve_default=False,
        ),
    ]
